class CountryCode {
  final String name;
  final String dialCode;
  final String isoCode;

  const CountryCode({
    required this.name,
    required this.dialCode,
    required this.isoCode,
  });

  /// Generates the flag emoji from the ISO 2-letter country code.
  String get flag {
    return isoCode.toUpperCase().split('').map((c) {
      return String.fromCharCode(c.codeUnitAt(0) + 127397);
    }).join();
  }

  /// Dial code digits only, no "+" (e.g. "964").
  String get rawCode => dialCode.replaceAll('+', '');
}

const CountryCode iraqCountryCode =
    CountryCode(name: 'Iraq', dialCode: '+964', isoCode: 'IQ');

const List<CountryCode> allCountryCodes = [
  // ── Middle East / default ────────────────────────────────────────────────
  CountryCode(name: 'Iraq', dialCode: '+964', isoCode: 'IQ'),
  CountryCode(name: 'Iran', dialCode: '+98', isoCode: 'IR'),
  CountryCode(name: 'Syria', dialCode: '+963', isoCode: 'SY'),
  CountryCode(name: 'Jordan', dialCode: '+962', isoCode: 'JO'),
  CountryCode(name: 'Lebanon', dialCode: '+961', isoCode: 'LB'),
  CountryCode(name: 'Kuwait', dialCode: '+965', isoCode: 'KW'),
  CountryCode(name: 'Saudi Arabia', dialCode: '+966', isoCode: 'SA'),
  CountryCode(name: 'Yemen', dialCode: '+967', isoCode: 'YE'),
  CountryCode(name: 'Oman', dialCode: '+968', isoCode: 'OM'),
  CountryCode(name: 'United Arab Emirates', dialCode: '+971', isoCode: 'AE'),
  CountryCode(name: 'Israel', dialCode: '+972', isoCode: 'IL'),
  CountryCode(name: 'Palestinian Territory', dialCode: '+970', isoCode: 'PS'),
  CountryCode(name: 'Bahrain', dialCode: '+973', isoCode: 'BH'),
  CountryCode(name: 'Qatar', dialCode: '+974', isoCode: 'QA'),
  CountryCode(name: 'Turkey', dialCode: '+90', isoCode: 'TR'),
  CountryCode(name: 'Egypt', dialCode: '+20', isoCode: 'EG'),
  CountryCode(name: 'Libya', dialCode: '+218', isoCode: 'LY'),
  CountryCode(name: 'Algeria', dialCode: '+213', isoCode: 'DZ'),
  CountryCode(name: 'Morocco', dialCode: '+212', isoCode: 'MA'),
  CountryCode(name: 'Tunisia', dialCode: '+216', isoCode: 'TN'),
  CountryCode(name: 'Sudan', dialCode: '+249', isoCode: 'SD'),
  CountryCode(name: 'Afghanistan', dialCode: '+93', isoCode: 'AF'),
  CountryCode(name: 'Pakistan', dialCode: '+92', isoCode: 'PK'),
  // ── Europe ───────────────────────────────────────────────────────────────
  CountryCode(name: 'Albania', dialCode: '+355', isoCode: 'AL'),
  CountryCode(name: 'Andorra', dialCode: '+376', isoCode: 'AD'),
  CountryCode(name: 'Armenia', dialCode: '+374', isoCode: 'AM'),
  CountryCode(name: 'Austria', dialCode: '+43', isoCode: 'AT'),
  CountryCode(name: 'Azerbaijan', dialCode: '+994', isoCode: 'AZ'),
  CountryCode(name: 'Belarus', dialCode: '+375', isoCode: 'BY'),
  CountryCode(name: 'Belgium', dialCode: '+32', isoCode: 'BE'),
  CountryCode(name: 'Bosnia & Herzegovina', dialCode: '+387', isoCode: 'BA'),
  CountryCode(name: 'Bulgaria', dialCode: '+359', isoCode: 'BG'),
  CountryCode(name: 'Croatia', dialCode: '+385', isoCode: 'HR'),
  CountryCode(name: 'Cyprus', dialCode: '+357', isoCode: 'CY'),
  CountryCode(name: 'Czech Republic', dialCode: '+420', isoCode: 'CZ'),
  CountryCode(name: 'Denmark', dialCode: '+45', isoCode: 'DK'),
  CountryCode(name: 'Estonia', dialCode: '+372', isoCode: 'EE'),
  CountryCode(name: 'Finland', dialCode: '+358', isoCode: 'FI'),
  CountryCode(name: 'France', dialCode: '+33', isoCode: 'FR'),
  CountryCode(name: 'Georgia', dialCode: '+995', isoCode: 'GE'),
  CountryCode(name: 'Germany', dialCode: '+49', isoCode: 'DE'),
  CountryCode(name: 'Greece', dialCode: '+30', isoCode: 'GR'),
  CountryCode(name: 'Hungary', dialCode: '+36', isoCode: 'HU'),
  CountryCode(name: 'Iceland', dialCode: '+354', isoCode: 'IS'),
  CountryCode(name: 'Ireland', dialCode: '+353', isoCode: 'IE'),
  CountryCode(name: 'Italy', dialCode: '+39', isoCode: 'IT'),
  CountryCode(name: 'Kazakhstan', dialCode: '+7', isoCode: 'KZ'),
  CountryCode(name: 'Kosovo', dialCode: '+383', isoCode: 'XK'),
  CountryCode(name: 'Latvia', dialCode: '+371', isoCode: 'LV'),
  CountryCode(name: 'Liechtenstein', dialCode: '+423', isoCode: 'LI'),
  CountryCode(name: 'Lithuania', dialCode: '+370', isoCode: 'LT'),
  CountryCode(name: 'Luxembourg', dialCode: '+352', isoCode: 'LU'),
  CountryCode(name: 'Malta', dialCode: '+356', isoCode: 'MT'),
  CountryCode(name: 'Moldova', dialCode: '+373', isoCode: 'MD'),
  CountryCode(name: 'Monaco', dialCode: '+377', isoCode: 'MC'),
  CountryCode(name: 'Montenegro', dialCode: '+382', isoCode: 'ME'),
  CountryCode(name: 'Netherlands', dialCode: '+31', isoCode: 'NL'),
  CountryCode(name: 'North Macedonia', dialCode: '+389', isoCode: 'MK'),
  CountryCode(name: 'Norway', dialCode: '+47', isoCode: 'NO'),
  CountryCode(name: 'Poland', dialCode: '+48', isoCode: 'PL'),
  CountryCode(name: 'Portugal', dialCode: '+351', isoCode: 'PT'),
  CountryCode(name: 'Romania', dialCode: '+40', isoCode: 'RO'),
  CountryCode(name: 'Russia', dialCode: '+7', isoCode: 'RU'),
  CountryCode(name: 'San Marino', dialCode: '+378', isoCode: 'SM'),
  CountryCode(name: 'Serbia', dialCode: '+381', isoCode: 'RS'),
  CountryCode(name: 'Slovakia', dialCode: '+421', isoCode: 'SK'),
  CountryCode(name: 'Slovenia', dialCode: '+386', isoCode: 'SI'),
  CountryCode(name: 'Spain', dialCode: '+34', isoCode: 'ES'),
  CountryCode(name: 'Sweden', dialCode: '+46', isoCode: 'SE'),
  CountryCode(name: 'Switzerland', dialCode: '+41', isoCode: 'CH'),
  CountryCode(name: 'Ukraine', dialCode: '+380', isoCode: 'UA'),
  CountryCode(name: 'United Kingdom', dialCode: '+44', isoCode: 'GB'),
  CountryCode(name: 'Vatican City', dialCode: '+39', isoCode: 'VA'),
  // ── Asia ─────────────────────────────────────────────────────────────────
  CountryCode(name: 'Bangladesh', dialCode: '+880', isoCode: 'BD'),
  CountryCode(name: 'Bhutan', dialCode: '+975', isoCode: 'BT'),
  CountryCode(name: 'Brunei', dialCode: '+673', isoCode: 'BN'),
  CountryCode(name: 'Cambodia', dialCode: '+855', isoCode: 'KH'),
  CountryCode(name: 'China', dialCode: '+86', isoCode: 'CN'),
  CountryCode(name: 'Hong Kong', dialCode: '+852', isoCode: 'HK'),
  CountryCode(name: 'India', dialCode: '+91', isoCode: 'IN'),
  CountryCode(name: 'Indonesia', dialCode: '+62', isoCode: 'ID'),
  CountryCode(name: 'Japan', dialCode: '+81', isoCode: 'JP'),
  CountryCode(name: 'Kyrgyzstan', dialCode: '+996', isoCode: 'KG'),
  CountryCode(name: 'Laos', dialCode: '+856', isoCode: 'LA'),
  CountryCode(name: 'Macau', dialCode: '+853', isoCode: 'MO'),
  CountryCode(name: 'Malaysia', dialCode: '+60', isoCode: 'MY'),
  CountryCode(name: 'Maldives', dialCode: '+960', isoCode: 'MV'),
  CountryCode(name: 'Mongolia', dialCode: '+976', isoCode: 'MN'),
  CountryCode(name: 'Myanmar', dialCode: '+95', isoCode: 'MM'),
  CountryCode(name: 'Nepal', dialCode: '+977', isoCode: 'NP'),
  CountryCode(name: 'North Korea', dialCode: '+850', isoCode: 'KP'),
  CountryCode(name: 'Philippines', dialCode: '+63', isoCode: 'PH'),
  CountryCode(name: 'Singapore', dialCode: '+65', isoCode: 'SG'),
  CountryCode(name: 'South Korea', dialCode: '+82', isoCode: 'KR'),
  CountryCode(name: 'Sri Lanka', dialCode: '+94', isoCode: 'LK'),
  CountryCode(name: 'Taiwan', dialCode: '+886', isoCode: 'TW'),
  CountryCode(name: 'Tajikistan', dialCode: '+992', isoCode: 'TJ'),
  CountryCode(name: 'Thailand', dialCode: '+66', isoCode: 'TH'),
  CountryCode(name: 'Timor-Leste', dialCode: '+670', isoCode: 'TL'),
  CountryCode(name: 'Turkmenistan', dialCode: '+993', isoCode: 'TM'),
  CountryCode(name: 'Uzbekistan', dialCode: '+998', isoCode: 'UZ'),
  CountryCode(name: 'Vietnam', dialCode: '+84', isoCode: 'VN'),
  // ── Americas ─────────────────────────────────────────────────────────────
  CountryCode(name: 'Antigua & Barbuda', dialCode: '+1268', isoCode: 'AG'),
  CountryCode(name: 'Argentina', dialCode: '+54', isoCode: 'AR'),
  CountryCode(name: 'Bahamas', dialCode: '+1242', isoCode: 'BS'),
  CountryCode(name: 'Barbados', dialCode: '+1246', isoCode: 'BB'),
  CountryCode(name: 'Belize', dialCode: '+501', isoCode: 'BZ'),
  CountryCode(name: 'Bolivia', dialCode: '+591', isoCode: 'BO'),
  CountryCode(name: 'Brazil', dialCode: '+55', isoCode: 'BR'),
  CountryCode(name: 'Canada', dialCode: '+1', isoCode: 'CA'),
  CountryCode(name: 'Chile', dialCode: '+56', isoCode: 'CL'),
  CountryCode(name: 'Colombia', dialCode: '+57', isoCode: 'CO'),
  CountryCode(name: 'Costa Rica', dialCode: '+506', isoCode: 'CR'),
  CountryCode(name: 'Cuba', dialCode: '+53', isoCode: 'CU'),
  CountryCode(name: 'Dominica', dialCode: '+1767', isoCode: 'DM'),
  CountryCode(name: 'Dominican Republic', dialCode: '+1809', isoCode: 'DO'),
  CountryCode(name: 'Ecuador', dialCode: '+593', isoCode: 'EC'),
  CountryCode(name: 'El Salvador', dialCode: '+503', isoCode: 'SV'),
  CountryCode(name: 'Grenada', dialCode: '+1473', isoCode: 'GD'),
  CountryCode(name: 'Guatemala', dialCode: '+502', isoCode: 'GT'),
  CountryCode(name: 'Guyana', dialCode: '+592', isoCode: 'GY'),
  CountryCode(name: 'Haiti', dialCode: '+509', isoCode: 'HT'),
  CountryCode(name: 'Honduras', dialCode: '+504', isoCode: 'HN'),
  CountryCode(name: 'Jamaica', dialCode: '+1876', isoCode: 'JM'),
  CountryCode(name: 'Mexico', dialCode: '+52', isoCode: 'MX'),
  CountryCode(name: 'Nicaragua', dialCode: '+505', isoCode: 'NI'),
  CountryCode(name: 'Panama', dialCode: '+507', isoCode: 'PA'),
  CountryCode(name: 'Paraguay', dialCode: '+595', isoCode: 'PY'),
  CountryCode(name: 'Peru', dialCode: '+51', isoCode: 'PE'),
  CountryCode(name: 'Saint Kitts & Nevis', dialCode: '+1869', isoCode: 'KN'),
  CountryCode(name: 'Saint Lucia', dialCode: '+1758', isoCode: 'LC'),
  CountryCode(name: 'Saint Vincent', dialCode: '+1784', isoCode: 'VC'),
  CountryCode(name: 'Suriname', dialCode: '+597', isoCode: 'SR'),
  CountryCode(name: 'Trinidad & Tobago', dialCode: '+1868', isoCode: 'TT'),
  CountryCode(name: 'United States', dialCode: '+1', isoCode: 'US'),
  CountryCode(name: 'Uruguay', dialCode: '+598', isoCode: 'UY'),
  CountryCode(name: 'Venezuela', dialCode: '+58', isoCode: 'VE'),
  // ── Africa ───────────────────────────────────────────────────────────────
  CountryCode(name: 'Angola', dialCode: '+244', isoCode: 'AO'),
  CountryCode(name: 'Benin', dialCode: '+229', isoCode: 'BJ'),
  CountryCode(name: 'Botswana', dialCode: '+267', isoCode: 'BW'),
  CountryCode(name: 'Burkina Faso', dialCode: '+226', isoCode: 'BF'),
  CountryCode(name: 'Burundi', dialCode: '+257', isoCode: 'BI'),
  CountryCode(name: 'Cabo Verde', dialCode: '+238', isoCode: 'CV'),
  CountryCode(name: 'Cameroon', dialCode: '+237', isoCode: 'CM'),
  CountryCode(name: 'Central African Republic', dialCode: '+236', isoCode: 'CF'),
  CountryCode(name: 'Chad', dialCode: '+235', isoCode: 'TD'),
  CountryCode(name: 'Comoros', dialCode: '+269', isoCode: 'KM'),
  CountryCode(name: 'Congo', dialCode: '+242', isoCode: 'CG'),
  CountryCode(name: 'DR Congo', dialCode: '+243', isoCode: 'CD'),
  CountryCode(name: 'Djibouti', dialCode: '+253', isoCode: 'DJ'),
  CountryCode(name: 'Equatorial Guinea', dialCode: '+240', isoCode: 'GQ'),
  CountryCode(name: 'Eritrea', dialCode: '+291', isoCode: 'ER'),
  CountryCode(name: 'Eswatini', dialCode: '+268', isoCode: 'SZ'),
  CountryCode(name: 'Ethiopia', dialCode: '+251', isoCode: 'ET'),
  CountryCode(name: 'Gabon', dialCode: '+241', isoCode: 'GA'),
  CountryCode(name: 'Gambia', dialCode: '+220', isoCode: 'GM'),
  CountryCode(name: 'Ghana', dialCode: '+233', isoCode: 'GH'),
  CountryCode(name: 'Guinea', dialCode: '+224', isoCode: 'GN'),
  CountryCode(name: 'Guinea-Bissau', dialCode: '+245', isoCode: 'GW'),
  CountryCode(name: 'Ivory Coast', dialCode: '+225', isoCode: 'CI'),
  CountryCode(name: 'Kenya', dialCode: '+254', isoCode: 'KE'),
  CountryCode(name: 'Lesotho', dialCode: '+266', isoCode: 'LS'),
  CountryCode(name: 'Liberia', dialCode: '+231', isoCode: 'LR'),
  CountryCode(name: 'Madagascar', dialCode: '+261', isoCode: 'MG'),
  CountryCode(name: 'Malawi', dialCode: '+265', isoCode: 'MW'),
  CountryCode(name: 'Mali', dialCode: '+223', isoCode: 'ML'),
  CountryCode(name: 'Mauritania', dialCode: '+222', isoCode: 'MR'),
  CountryCode(name: 'Mauritius', dialCode: '+230', isoCode: 'MU'),
  CountryCode(name: 'Mozambique', dialCode: '+258', isoCode: 'MZ'),
  CountryCode(name: 'Namibia', dialCode: '+264', isoCode: 'NA'),
  CountryCode(name: 'Niger', dialCode: '+227', isoCode: 'NE'),
  CountryCode(name: 'Nigeria', dialCode: '+234', isoCode: 'NG'),
  CountryCode(name: 'Rwanda', dialCode: '+250', isoCode: 'RW'),
  CountryCode(name: 'São Tomé & Príncipe', dialCode: '+239', isoCode: 'ST'),
  CountryCode(name: 'Senegal', dialCode: '+221', isoCode: 'SN'),
  CountryCode(name: 'Seychelles', dialCode: '+248', isoCode: 'SC'),
  CountryCode(name: 'Sierra Leone', dialCode: '+232', isoCode: 'SL'),
  CountryCode(name: 'Somalia', dialCode: '+252', isoCode: 'SO'),
  CountryCode(name: 'South Africa', dialCode: '+27', isoCode: 'ZA'),
  CountryCode(name: 'South Sudan', dialCode: '+211', isoCode: 'SS'),
  CountryCode(name: 'Tanzania', dialCode: '+255', isoCode: 'TZ'),
  CountryCode(name: 'Togo', dialCode: '+228', isoCode: 'TG'),
  CountryCode(name: 'Uganda', dialCode: '+256', isoCode: 'UG'),
  CountryCode(name: 'Zambia', dialCode: '+260', isoCode: 'ZM'),
  CountryCode(name: 'Zimbabwe', dialCode: '+263', isoCode: 'ZW'),
  // ── Oceania ──────────────────────────────────────────────────────────────
  CountryCode(name: 'Australia', dialCode: '+61', isoCode: 'AU'),
  CountryCode(name: 'Fiji', dialCode: '+679', isoCode: 'FJ'),
  CountryCode(name: 'Kiribati', dialCode: '+686', isoCode: 'KI'),
  CountryCode(name: 'Marshall Islands', dialCode: '+692', isoCode: 'MH'),
  CountryCode(name: 'Micronesia', dialCode: '+691', isoCode: 'FM'),
  CountryCode(name: 'Nauru', dialCode: '+674', isoCode: 'NR'),
  CountryCode(name: 'New Zealand', dialCode: '+64', isoCode: 'NZ'),
  CountryCode(name: 'Palau', dialCode: '+680', isoCode: 'PW'),
  CountryCode(name: 'Papua New Guinea', dialCode: '+675', isoCode: 'PG'),
  CountryCode(name: 'Samoa', dialCode: '+685', isoCode: 'WS'),
  CountryCode(name: 'Solomon Islands', dialCode: '+677', isoCode: 'SB'),
  CountryCode(name: 'Tonga', dialCode: '+676', isoCode: 'TO'),
  CountryCode(name: 'Tuvalu', dialCode: '+688', isoCode: 'TV'),
  CountryCode(name: 'Vanuatu', dialCode: '+678', isoCode: 'VU'),
];
